export const ONWARD_DRAFT_COOKIE = "bye4o_onward_draft";

export const MAX_ONWARD_MESSAGE_LENGTH = 1000;
export const MAX_ONWARD_QUERY_LIMIT = 50;
export const DEFAULT_ONWARD_QUERY_LIMIT = 20;

export const ONWARD_DRAFT_COOKIE_MAX_AGE_SECONDS = 60 * 60 * 24 * 30;
export const ONWARD_RESTORE_RETENTION_DAYS = 7;
export const ONWARD_RESTORE_RETENTION_MS =
  ONWARD_RESTORE_RETENTION_DAYS * 24 * 60 * 60 * 1000;
